[package]
name = "kyun"
version = "0.1.0"
authors = ["fi-le <info@fi-le.net>", "Philipp Flenker <hello@philippflenker.com>"]
edition = "2018"

# Based on the editor hecto by Phillip Flenker

[dependencies]
crossterm = "0.22.1"
unicode-segmentation = "1"
